version: "3.0"

#Create a network that links containers
services:
  #Create the Melodic Container
  ros-melodic:
    build:
     context: .
     dockerfile: melodic.Dockerfile
    tty: true
    stdin_open: true
    privileged: true
    network_mode: "host"
    volumes:
      #- ../catkin_ws/build:/root/catkin_ws/build
      - ../catkin_ws/src:/root/catkin_ws/src
      - ../shared_folder:/root/shared_folder
      - ../shared_folder/.zshrc:/root/.zshrc:rw
      - ../shared_folder/.p10k.zsh:/root/.p10k.zsh:rw
      - ../shared_folder/.zsh_history:/root/.zsh_history:rw
      - ../shared_folder/.oh-my-zsh:/root/.oh-my-zsh
      - /dev/dri:/dev/dri
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /run/user/1000/at-spi/bus:/run/user/1000/at-spi/bus:ro
      - /var/run/dbus:/var/run/dbus
    ulimits:
     nofile:
       soft: 1024
       hard: 524288
    environment:
      - SETUP=/root/catkin_ws/devel/setup.bash
      - BUILDLIST= elevation_msgs traversability_mapping xsens_driver #Only these packages will be build
      - ROSPACKAGE=traversability_mapping
      - LAUNCHFILE=offline.launch
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      #- ROS_MASTER_URI=http://192.168.123.161:11311/
    command: ./root/shared_folder/melodic-launch.sh

  #Create the Noetic Container
  ros-noetic:
    build:
      context: .
      dockerfile: noetic.Dockerfile
    tty: true
    stdin_open: true
    privileged: true
    network_mode: "host"
    volumes:
      - ../catkin_ws/src:/root/catkin_ws/src
      - ../catkin_ws/build:/root/catkin_ws/build
      - ../catkin_ws/src/gps_waypoint_nav/.mapviz_config:/root/.mapviz_config:rw
      - ../shared_folder:/root/shared_folder
      - ../shared_folder/.zshrc:/root/.zshrc:rw
      - ../shared_folder/.p10k.zsh:/root/.p10k.zsh:rw
      - ../shared_folder/.zsh_history:/root/.zsh_history:rw
      - ../shared_folder/.oh-my-zsh:/root/.oh-my-zsh
      - /dev/dri:/dev/dri
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /run/user/1000/at-spi/bus:/run/user/1000/at-spi/bus:ro
      - /var/run/dbus:/var/run/dbus
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    environment:
      - SETUP=/root/catkin_ws/devel/setup.bash
      - BUILDLIST= elevation_mapping elevation_mapping_demos gps_waypoint_nav ig_lio metrics_extractor navigation_final_semfire_pilot ros_numpy unitree_legged_msgs unitree_legged_sdk rslidar_sdk go1_ros_interface kindr kindr_ros message_logger point_cloud_io go1_description octomap_server #Only these packages will be build
      - ROSPACKAGE= ig_lio
      - LAUNCHFILE= noetic_main_elev.launch
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      #- ROS_MASTER_URI=http://192.168.123.161:11311/
    command: ./root/shared_folder/noetic-launch.sh

  #Create the Tile Server Container
  tile-server:
    build:
      context: .
      dockerfile: tilemap.Dockerfile
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    environment:
    #  UPDATES: enabled
      THREADS: 24
    ports:
      - "8080:80"
    command: run  # Runs the server after the data is imported
